In [2]:
import numpy as np
import pandas as pd

In [5]:
l = [1,2,3,4,5, 6.0, 7.0, 'sam']
l, type(l)

([1, 2, 3, 4, 5, 6.0, 7.0, 'sam'], list)

In [11]:
# numpy array
np.array(l), type(np.array(l))

(array(['1', '2', '3', '4', '5', '6.0', '7.0', 'sam'], dtype='<U32'),
 numpy.ndarray)

In [10]:
t = (1,2,3,4)
np.array(t), type(np.array(t))

(array([1, 2, 3, 4]), numpy.ndarray)

In [9]:
d = {'a':1, 'b':1, 'c':3}
np.array(d), type(np.array(d))

(array({'a': 1, 'b': 1, 'c': 3}, dtype=object), numpy.ndarray)

In [13]:
#ndarray - n dimension
a1 = np.array([3,4,5,6])
a1

array([3, 4, 5, 6])

In [17]:
# 2-d array
a = np.array([[1,2], [3,4]]) # row index, column index
a

array([[1, 2],
       [3, 4]])

In [18]:
pd.DataFrame(a)

0  1
0  1  2
1  3  4

In [19]:
# 3-d array
a = np.array([[[1,2], [3,4]]]) # row index, column index
a

array([[[1, 2],
        [3, 4]]])

In [20]:
# 2-d array
a = np.array([[1,2], [3,4]]) # row index, column index
a

array([[1, 2],
       [3, 4]])

In [22]:
a[0]

array([1, 2])

In [23]:
a[1]

array([3, 4])

In [24]:
a[0][0]

1

In [30]:
v = [[[1,2], [2], [3]]]

In [33]:
v[0][0][0]

1

In [34]:
# 3-d array
b = np.array([[[1,2,3], [3,4,5], [6,7,8]]])
b

array([[[1, 2, 3],
        [3, 4, 5],
        [6, 7, 8]]])

In [38]:
b[0][1][1]

4

In [39]:
b[0,1,1]

4

In [40]:
b[0][1]

array([3, 4, 5])

In [41]:
b[0,1]

array([3, 4, 5])

In [48]:
a1 = np.array([3,4,5,6,3.0])
a1

array([3., 4., 5., 6., 3.])

In [49]:
a1[2]

5.0

In [50]:
z = [1,2,3,4]

In [52]:
# 0 dimension array
np.array(z, ndmin=0)

array([1, 2, 3, 4])

In [53]:
# 1 dimension array
np.array(z, ndmin=1)

array([1, 2, 3, 4])

In [54]:
# 2 dimension array
np.array(z, ndmin=2)

array([[1, 2, 3, 4]])

In [55]:
# 3 dimension array
np.array(z, ndmin=3)

array([[[1, 2, 3, 4]]])

In [57]:
# 4 dimension array
q = np.array(z, ndmin=4)
q

array([[[[1, 2, 3, 4]]]])

In [59]:
q[0,0,0,2], q[0][0][0][2]

(3, 3)

In [60]:
np.asarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [61]:
# 2d-array = matrix
np.mat([1,2,3,4,5])

matrix([[1, 2, 3, 4, 5]])

In [63]:
#creating 2d-arrays & matrix
np.array([[1,2,3]]), np.array([1,2,3], ndmin=2), np.mat([1,2,3]), np.asarray([[1,2,3]])


(array([[1, 2, 3]]),
 array([[1, 2, 3]]),
 matrix([[1, 2, 3]]),
 array([[1, 2, 3]]))

In [64]:
type(np.mat([1,2,3]))

numpy.matrix

In [65]:
np.array(np.mat([1,2,3]))

array([[1, 2, 3]])

In [66]:
np.asarray(np.mat([1,2,3]))

array([[1, 2, 3]])

In [67]:
s = '123'
i = int(s)
i, type(i)

(123, int)

In [74]:
# using custom function to create an array
np.fromfunction(lambda i,j: i==j, shape=(1,3)) # shape is arrays of n dimension | (3,3) -> 2-d: x,y

array([[ True, False, False]])

##### to understand the dimension of the array
- Step1: Count the number of elements in the shape parameter. eg. shape=(1,3) count of elements = 2 i.e. 2d-array
- Step2: Check the values of the elements. eg. shape=(1,3)-> 2d array with 1 row and 3 columns

In [75]:
pd.DataFrame(np.fromfunction(lambda i,j: i==j, shape=(1,3)))

0      1      2
0  True  False  False

In [76]:
np.fromfunction(lambda i,j: i*j, (4,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [77]:
np.fromfunction(lambda i,j: i*j, (4,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6],
       [0, 3, 6, 9]])

In [78]:
np.fromfunction(lambda i,j,k: i*j*k, (4,3,2)) # 3d-array of shape 4*3*2 z = 4, y= 3, x=2

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 1.],
        [0., 2.]],

       [[0., 0.],
        [0., 2.],
        [0., 4.]],

       [[0., 0.],
        [0., 3.],
        [0., 6.]]])

In [80]:
np.fromfunction(lambda i,j,k: i*j*k, (2,4,5), dtype = int) # 3d-array of shape 2*4*5 z = 2, y= 4, x=5

array([[[ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0]],

       [[ 0,  0,  0,  0,  0],
        [ 0,  1,  2,  3,  4],
        [ 0,  2,  4,  6,  8],
        [ 0,  3,  6,  9, 12]]])

In [85]:
# 4-d array
np.fromfunction(lambda i,j,k,l: i*j*k*l, (3,3,2,2), dtype = int)

array([[[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 1]],

        [[0, 0],
         [0, 2]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 2]],

        [[0, 0],
         [0, 4]]]])

In [86]:
d3 = np.fromfunction(lambda i,j,k: i*j*k, (2,4,5), dtype = int)
d3

array([[[ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0]],

       [[ 0,  0,  0,  0,  0],
        [ 0,  1,  2,  3,  4],
        [ 0,  2,  4,  6,  8],
        [ 0,  3,  6,  9, 12]]])

In [87]:
d3.dtype

dtype('int64')

In [88]:
d3.ndim

3

In [89]:
d3.size

40

In [90]:
d3.shape

(2, 4, 5)

In [91]:
# by default dataframes can only convert 2d arrays(matrices) into dataframe
d2 = np.fromfunction(lambda a,b: a+b, (4,3), dtype=int)
pd.DataFrame(d2)

0  1  2
0  0  1  2
1  1  2  3
2  2  3  4
3  3  4  5