In [1]:
import numpy as np
import pandas as pd

In [11]:
# array with random numbers
np.random.rand(10,4)

array([[0.21845268, 0.62239406, 0.50713915, 0.85262777],
       [0.83675653, 0.81264803, 0.14891323, 0.938428  ],
       [0.57015228, 0.89863203, 0.73694921, 0.37619013],
       [0.31791459, 0.29312271, 0.50432028, 0.33224628],
       [0.52144377, 0.92750585, 0.68705423, 0.60735556],
       [0.11745286, 0.30855929, 0.61125552, 0.04178404],
       [0.83319172, 0.58523654, 0.56417244, 0.32410095],
       [0.23264649, 0.19660819, 0.04843909, 0.58716608],
       [0.93207478, 0.8188622 , 0.5630324 , 0.36870639],
       [0.11435873, 0.93622694, 0.33623415, 0.24570241]])

In [9]:
pd.DataFrame(np.random.rand(8,3))

0         1         2
0  0.242886  0.513364  0.495704
1  0.895681  0.929483  0.766992
2  0.168820  0.250827  0.369688
3  0.680198  0.348946  0.378287
4  0.970723  0.249263  0.042704
5  0.011694  0.611264  0.753281
6  0.149580  0.404960  0.689515
7  0.618613  0.377874  0.493398

In [8]:
# random int
np.random.randint(4,50)

9

In [3]:
# array with standard normal distribution
np.random.randn(10,4)

array([[ 0.35922366,  0.83141901,  0.09775394, -0.95802869],
       [ 1.38576445,  0.59551505,  1.11028976, -0.35048862],
       [ 0.69760055, -1.77563782, -0.18133948, -0.34650367],
       [ 1.93921243,  1.2223894 ,  0.81000528, -0.01016362],
       [-1.0157331 ,  0.80327373, -0.83095093,  0.88231314],
       [ 0.89081421, -0.2137045 ,  0.26493118,  1.80251492],
       [ 0.88055776, -1.10699194, -0.95836261,  0.88055172],
       [ 0.39782745,  0.75198545, -0.3945117 , -0.7333202 ],
       [-0.03772024, -0.93885026,  1.38673773, -0.47256063],
       [ 0.61008851,  0.64821999, -0.58385996, -1.55219813]])

In [13]:
np.fromfunction(lambda i,j: i*j, shape=(2,2), dtype=int) # 2-D

array([[0, 0],
       [0, 1]])

##### to understand the dimension of the array
- Step1: Count the number of elements in the shape parameter. eg. shape=(1,3) count of elements = 2 i.e. 2d-array
- Step2: Check the values of the elements. eg. shape=(1,3)-> 2d array with 1 row and 3 columns

In [12]:
a = np.array([1,2,3,4,5,6,7,8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
# reshaping the array

## converting 1-D array to 2-D array (pay attention to the size of the original array)
a.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
# 2-d array shape(a,b)- 2 elements hence 2-D array
# 3-d array shape(a,b,c) - 3 elements hence 3-D array

array([1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
# 8 elements
# reshape 1-D array to 3-D array
a.reshape(1,2,4)

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]]])

In [20]:
a.reshape(2,4,-15674802020)

array([[[1],
        [2],
        [3],
        [4]],

       [[5],
        [6],
        [7],
        [8]]])

In [21]:
b = np.array([1,2,3,4,5,6,7,8,9])
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
b.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
b.reshape(1,3,3)

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [25]:
b.reshape(3,3,-12324)

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]])

In [26]:
b.reshape(-1, 9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [27]:
b.reshape(-1,1,9)

array([[[1, 2, 3, 4, 5, 6, 7, 8, 9]]])

In [29]:
a = np.random.rand(10,4)
a

array([[0.93118998, 0.18829013, 0.9570622 , 0.87605589],
       [0.56034666, 0.5129741 , 0.96257776, 0.66779441],
       [0.91799134, 0.24626723, 0.16322566, 0.03655528],
       [0.67249311, 0.09203774, 0.97593954, 0.72332439],
       [0.32399104, 0.82993874, 0.8482632 , 0.30739956],
       [0.08198895, 0.4793361 , 0.43301267, 0.79992676],
       [0.83969991, 0.93907689, 0.50677048, 0.022484  ],
       [0.98724496, 0.93289274, 0.08209533, 0.81630752],
       [0.00117562, 0.95601834, 0.92886284, 0.12991478],
       [0.51177874, 0.89184701, 0.65528448, 0.90083601]])

In [30]:
# 2d-array to 4-d array
a.reshape(2,5,2,2)

array([[[[0.93118998, 0.18829013],
         [0.9570622 , 0.87605589]],

        [[0.56034666, 0.5129741 ],
         [0.96257776, 0.66779441]],

        [[0.91799134, 0.24626723],
         [0.16322566, 0.03655528]],

        [[0.67249311, 0.09203774],
         [0.97593954, 0.72332439]],

        [[0.32399104, 0.82993874],
         [0.8482632 , 0.30739956]]],


       [[[0.08198895, 0.4793361 ],
         [0.43301267, 0.79992676]],

        [[0.83969991, 0.93907689],
         [0.50677048, 0.022484  ]],

        [[0.98724496, 0.93289274],
         [0.08209533, 0.81630752]],

        [[0.00117562, 0.95601834],
         [0.92886284, 0.12991478]],

        [[0.51177874, 0.89184701],
         [0.65528448, 0.90083601]]]])

In [41]:
list(range(4,10))

[4, 5, 6, 7, 8, 9]

In [42]:
a1 = np.arange(4,10.0)
a1

array([4., 5., 6., 7., 8., 9.])

In [43]:
arr = np.random.rand(4,5)
arr

array([[0.46617908, 0.65351808, 0.47384507, 0.84312858, 0.25180769],
       [0.47420594, 0.23448313, 0.24319808, 0.23420575, 0.65605767],
       [0.25339523, 0.69900548, 0.55072312, 0.56566748, 0.99398216],
       [0.45865349, 0.34536143, 0.74467825, 0.91250078, 0.86110358]])

In [45]:
arr[0,0], arr[0][0]

(0.4661790839473533, 0.4661790839473533)

In [46]:
arr[arr > 0.5]

array([0.65351808, 0.84312858, 0.65605767, 0.69900548, 0.55072312,
       0.56566748, 0.99398216, 0.74467825, 0.91250078, 0.86110358])

In [47]:
arr[[1,2], [2]]

array([0.24319808, 0.55072312])

In [48]:
arr[1,2]

0.24319807760810663

In [ ]:
[[1,2,3,4],[5,6,7,8], [9,10,11,12]]

In [49]:
arr[2]

array([0.25339523, 0.69900548, 0.55072312, 0.56566748, 0.99398216])

In [50]:
arr

array([[0.46617908, 0.65351808, 0.47384507, 0.84312858, 0.25180769],
       [0.47420594, 0.23448313, 0.24319808, 0.23420575, 0.65605767],
       [0.25339523, 0.69900548, 0.55072312, 0.56566748, 0.99398216],
       [0.45865349, 0.34536143, 0.74467825, 0.91250078, 0.86110358]])

In [52]:
arr[[2,3], [1]]

array([0.69900548, 0.34536143])

In [55]:
df = pd.DataFrame(arr)
df

0         1         2         3         4
0  0.466179  0.653518  0.473845  0.843129  0.251808
1  0.474206  0.234483  0.243198  0.234206  0.656058
2  0.253395  0.699005  0.550723  0.565667  0.993982
3  0.458653  0.345361  0.744678  0.912501  0.861104

In [57]:
df.iloc[2:4, 1]

2    0.699005
3    0.345361
Name: 1, dtype: float64

In [58]:
df.to_numpy()

array([[0.46617908, 0.65351808, 0.47384507, 0.84312858, 0.25180769],
       [0.47420594, 0.23448313, 0.24319808, 0.23420575, 0.65605767],
       [0.25339523, 0.69900548, 0.55072312, 0.56566748, 0.99398216],
       [0.45865349, 0.34536143, 0.74467825, 0.91250078, 0.86110358]])

In [59]:
arr[1:3, 0:3]

array([[0.47420594, 0.23448313, 0.24319808],
       [0.25339523, 0.69900548, 0.55072312]])

In [60]:
arr[1:3, [0,1,2]]

array([[0.47420594, 0.23448313, 0.24319808],
       [0.25339523, 0.69900548, 0.55072312]])

In [61]:
arr

array([[0.46617908, 0.65351808, 0.47384507, 0.84312858, 0.25180769],
       [0.47420594, 0.23448313, 0.24319808, 0.23420575, 0.65605767],
       [0.25339523, 0.69900548, 0.55072312, 0.56566748, 0.99398216],
       [0.45865349, 0.34536143, 0.74467825, 0.91250078, 0.86110358]])

In [62]:
arr[0][0] = 0.123
arr

array([[0.123     , 0.65351808, 0.47384507, 0.84312858, 0.25180769],
       [0.47420594, 0.23448313, 0.24319808, 0.23420575, 0.65605767],
       [0.25339523, 0.69900548, 0.55072312, 0.56566748, 0.99398216],
       [0.45865349, 0.34536143, 0.74467825, 0.91250078, 0.86110358]])

In [64]:
a = np.array([[1,2],[3,4]])
b = np.array([[2,3],[4,5]])

In [65]:
a

array([[1, 2],
       [3, 4]])

In [66]:
b

array([[2, 3],
       [4, 5]])

In [67]:
# element multiplication
a*b

array([[ 2,  6],
       [12, 20]])

In [68]:
# matrix multiplication
m = a@b
m

array([[10, 13],
       [22, 29]])

In [69]:
6/0

ZeroDivisionError: division by zero

In [70]:
m/0

/var/folders/8c/xhhzc929045973qqkytbdr6h0000gn/T/ipykernel_3233/3791875896.py:1: RuntimeWarning: divide by zero encountered in divide
  m/0


array([[inf, inf],
       [inf, inf]])

In [72]:
a

array([[1, 2],
       [3, 4]])

In [71]:
a*2

array([[2, 4],
       [6, 8]])

In [74]:
a+2

array([[3, 4],
       [5, 6]])

In [75]:
a+b

array([[3, 5],
       [7, 9]])

In [76]:
2**3

8

In [77]:
pow(a,2)

array([[ 1,  4],
       [ 9, 16]])

In [79]:
a

array([[1, 2],
       [3, 4]])

In [78]:
a.max()

4

In [80]:
a.min()

1

In [81]:
a.T

array([[1, 3],
       [2, 4]])

In [82]:
a/2

array([[0.5, 1. ],
       [1.5, 2. ]])

In [83]:
a-b

array([[-1, -1],
       [-1, -1]])

In [84]:
a/b

array([[0.5       , 0.66666667],
       [0.75      , 0.8       ]])

In [85]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [86]:
np.exp(a)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [87]:
np.log(a)

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436]])

In [91]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [92]:
np.ones((3,4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [93]:
5 + np.zeros((3,4), dtype = int)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [94]:
np.log10(5) * np.ones((2,3))

array([[0.69897, 0.69897, 0.69897],
       [0.69897, 0.69897, 0.69897]])

In [98]:
np.linspace(2,6,10, endpoint=True) # linspace(start, stop, size of array)

array([2.        , 2.44444444, 2.88888889, 3.33333333, 3.77777778,
       4.22222222, 4.66666667, 5.11111111, 5.55555556, 6.        ])

In [99]:
np.linspace(2,6,10, endpoint=False)

array([2. , 2.4, 2.8, 3.2, 3.6, 4. , 4.4, 4.8, 5.2, 5.6])

In [100]:
np.linspace(2,6,10, endpoint=False).reshape(5,2)

array([[2. , 2.4],
       [2.8, 3.2],
       [3.6, 4. ],
       [4.4, 4.8],
       [5.2, 5.6]])

In [104]:
np.arange(2,40, 2) # 19 elements

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [96]:
a.size

4

In [97]:
a.shape

(2, 2)

In [115]:
x = np.array([1,2,3,4,5])
y = np.array([2,5,4,7,8])
z = np.array([3,6,7,3,4])

In [108]:
np.c_[x,y,z]

array([[1, 2, 3],
       [2, 5, 6],
       [3, 4, 7],
       [4, 7, 3],
       [5, 8, 4]])

In [117]:
x

array([1, 2, 3, 4, 5])

In [118]:
z

array([3, 6, 7, 3, 4])

In [120]:
y

array([2, 5, 4, 7, 8])

In [116]:
np.where(x==z,x,z)

array([3, 6, 7, 3, 4])

In [121]:
np.where(x==y,y,x)

array([1, 2, 3, 4, 5])

In [123]:
x

array([1, 2, 3, 4, 5])

In [122]:
np.where(x<4)

(array([0, 1, 2]),)

In [124]:
np.where(x>=3)

(array([2, 3, 4]),)